name: .NET Framework Build and Publish Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@master
      - uses: nuget/setup-nuget@v1.0.2
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: 'latest'
      - name: Setup MSBuild.exe
        uses: warrenbuckley/Setup-MSBuild@v1
      - run: msbuild -t:restore
      - run: msbuild -t:build
      - name: Nuget Add Source
        run: nuget sources Add -Name "github" -Source https://nuget.pkg.github.com/James-LeHa/index.json -UserName James-LeHa -Password ${{ secrets.GITHUB_TOKEN }}
      - name: Nuget SetAPIKey
        run: nuget setapikey ${{ secrets.GITHUB_TOKEN }} -Source "github"
      - name: Publish the package to GitHub packages
        run: nuget push bin\Debug\*.nupkg -source "github" -SkipDuplicate
